services:
  webserver:
    image: nodeserver:v1
    ports:
      - "8080:8080"
    depends_on:
      - "db"
  nginx:
    image: nginx:v1
    ports:
      - "80:80"
    volumes:
      - ./nginx/myconfig1.conf:/etc/nginx/conf.d/myconfig1.conf
    depends_on:
      - webserver

  db:
    image: postgres:18.0-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5431:5432"
